camera:
  H-FOV: 46.0  # Horizontal Field of View en grados
  V-FOV: 24.6  # Vertical Field of View en grados
  resolution:
    width: 640   # Resolución horizontal en píxeles
    height: 480  # Resolución vertical en píxeles