camera:
  H-FOV: 41.58
  V-FOV: 24.11
  focal_length_mm_x: 8.1928
  focal_length_mm_y: 8.1928
  focal_length_px: 1985.33
  focal_length_py: 1985.33
  resolution:
    height: 720
    width: 1280
  sensor_height_mm: 3.5
  sensor_width_mm: 6.22
