camera:
  H-FOV: 56.2  # Horizontal Field of View en grados
  V-FOV: 43.7  # Vertical Field of View en grados
  resolution:
    width: 346   # Resolución horizontal en píxeles
    height: 260  # Resolución vertical en píxeles